import type { Metadata } from "next";
import { Nunito } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";

export const metadata: Metadata = {
  title: "Keep it up!",
  description: "Generated by create next app",
};

const nunito = Nunito({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background font-sans", nunito.className)}
      >
        {children}
      </body>
    </html>
  );
}
